# Generated by Django 4.1.4 on 2024-01-25 05:05
import os
from django.db import migrations


def populate_s3_upload_path(apps, schema_editor):
    # `s3_upload_path` needs to be unique, but there are already existing records. this helps avoid an IntegrityError
    # https://docs.djangoproject.com/en/4.1/howto/writing-migrations/#migrations-that-add-unique-fields
    s3_bucket = 'getmybeats-audio'
    Audio = apps.get_model('GetMyBeatsApp', 'Audio')
    for audio in Audio.objects.all():
        basename = os.path.basename(str(audio.file_upload))
        audio.s3_upload_path = f's3://{s3_bucket}/{basename}'
        audio.save(update_fields=['s3_upload_path'])


class Migration(migrations.Migration):

    dependencies = [
        ('GetMyBeatsApp', '0005_audio_s3_upload_path'),
    ]

    operations = [
        migrations.RunPython(populate_s3_upload_path, reverse_code=migrations.RunPython.noop),
    ]
